### PR TITLE
Bump to 1.0.0

### PR DESCRIPTION
**Pull request by briancavalier**

### CODE REVIEW

**Comment by briancavalier** [comment]
Rebased.  Now that https://github.com/mostjs/multicast/issues/18 is merged, I think this is a go.  I'm barely awake tho, so gonna sleep on it :)

**Comment by TylorS** [comment]
Do we care about the failing tests on 0.12? They're not even directly related to most

**Comment by briancavalier** [comment]
Hmmm, eslint 3 officially dropped support for node < 4: https://github.com/eslint/eslint/issues/6679

**Comment by briancavalier** [comment]
I'm ok with removing node 0.12 from CI.  @TylorS @davidchase you cool w/that?

**Comment by davidchase** [comment]
👍

**Comment by TylorS** [comment]
:+1:

**Comment by unscriptable** [comment]
doo eet

**Pull request merged**
