### PR TITLE
Add xstream to performance benchmarks

### PR DESCRIPTION
**Pull request by staltz**
Just because.
:)

### CODE REVIEW

**Comment by TylorS** [comment]
Thanks @staltz. I know there are some perf tests you have in xstream that we don't have here, do you see any benefits to adding them here?

@briancavalier I'm definitely in favor of this :)

**Comment by staltz** [comment]
> I know there are some perf tests you have in xstream that we don't have here, do you see any benefits to adding them here?

Not necessarily. These tests are primarily to check most.js. I just wanted to add xstream because it's 2nd or 3rd in best performance, so it's nice to have it in the list.

**Comment by staltz** [comment]
Ideally these tests would live in some dedicated repo outside a specific stream lib.

**Comment by briancavalier** [comment]
:+1: I'm in favor as well.  Thanks, @staltz.

**Pull request merged**
