### PR TITLE
Ensure previous end events cannot disable recoverWith

### PR DESCRIPTION
**Pull request by briancavalier**
Avoids timing issue when recovering--see included unit test.

### CODE REVIEW

**Comment by briancavalier** [comment]
cc @davidchase

**Comment by davidchase** [comment]
It seems that these dont work:
```js
fromPromise(Promise.reject('Boom'))
.recoverWith(() => just(Promise.resolve('hi')).chain(fromPromise))
.observe(console.log.bind(console))
.catch(console.info.bind(console))
```

```js
awaitPromises(just(Promise.reject('boom')))
.recoverWith(() => just(Promise.resolve('hi')).chain(fromPromise))
.observe(console.log.bind(console))
.catch(console.info.bind(console))
```

http://www.webpackbin.com/41JwoKCkW

going to play around some more, see if i can help

**Comment by briancavalier** [comment]
Thanks for the additional test cases, @davidchase.  Clearly this needs more work :)

**Comment by davidchase** [comment]
seems like this is good to go?

**Comment by briancavalier** [comment]
Yeah, I think so.  I'd like to add unit tests for SafeSink, then I'll merge it.

**Comment by davidchase** [comment]
very cool, thanks again for taking the time on this one

**Comment by briancavalier** [comment]
Yay unit tests.  If travis says ok, I think this is good to merge.

**Pull request merged**
