### PR TITLE
generic parameter default for Disposable<A>

### PR DESCRIPTION
**Pull request by axefrog**
`Disposable<A>` takes a generic type argument which is almost never used in practice. To eliminate the unnecessary specificity in most use cases, I've added a generic parameter default of `any`, which changes the definition to:

```ts
export interface Disposable<A = any> {
  dispose(): void | Promise<A>;
}
```

### CODE REVIEW

**Comment by TylorS** [comment]
This requires TypeScript 2.3 for all users, I'm not sure if that is the right thing to do. Thoughts?

As an FYI though, It's been removed in `@most/core` to be only `Disposable`

**Comment by axefrog** [comment]
Ah yeah I suppose it could be considered a breaking change.

**Comment by briancavalier** [comment]
It seems like the right thing to do is just wait for most 2.0 (which will be based on `@most/core`).

@axefrog is the current type parameter causing any actual pain at the moment?

**Comment by axefrog** [comment]
No, I've switched to the new version of Most anyway.

**Comment by briancavalier** [comment]
Cool 😄

**Pull request closed without merging**
