### PR TITLE
Start a guide for contributing third-party extensions

### PR DESCRIPTION
**Pull request by unscriptable**
1. Cut from #93
2. Paste to new document
3. Profit

### CODE REVIEW

**Comment by unscriptable** [comment]
What needs to be added to make this a real thing?

**Comment by briancavalier** [comment]
This is a great idea!  A few things come to mind:

1. Showing actual (pseudo)code of the Source, Sink, and Disposable interfaces.  I'm not sure what the best format for this would be, though.
1. Providing more guidance on writing a new combinator:
    1. The first choice should always be to build a new combinator using existing ones.  You can do a *lot* with map, filter, flatMap, loop (or scan), sample, and combine.
    1. If it's not possible, or prohibitive (ie too much capturing required, etc.) to build from existing, then create a new Source+Sink.
1. Linking to a couple simple, existing combinators as examples, map and filter come to mind because they are dead simple.

Other ideas?

**Comment by briancavalier** [comment]
Another:

1. Showing an example of a producer Source, and maybe linking to an existing one.

**Comment by nackjicholson** [comment]
Excellent! Don't know of many open source projects that have documented explanations of their internal architecture to help new contributors. I really like the idea. :+1:

**Comment by briancavalier** [comment]
@unscriptable Do you want to work more on this?  Or did you want to hand it off?

**Comment by briancavalier** [comment]
I'd like to get an initiation version of this merged.  Do you think the right name for this document is "extending", or "architecture"?  Maybe "extending" with an "Architecture" section?

**Comment by briancavalier** [comment]
@unscriptable Is it cool with you if I commandeer this and combine it with info in #191?

**Comment by briancavalier** [comment]
Ok, new plan: gonna move the info here and in #191 to the wiki.

**Pull request closed without merging**
