### PR TITLE
fromArray: inline singly-invoked function.

### PR DESCRIPTION
**Pull request by StreetStrider**
Minor function inlining.

### CODE REVIEW

**Comment by davidchase** [comment]
LGTM probably will need to do the same for the mostjs/core

**Comment by StreetStrider** [comment]
@davidchase, where should I look? I don't see any other repo related to core.

**Comment by davidchase** [comment]
@StreetStrider sorry about the opaqueness we have been working on a new or rather more core modular for most at https://github.com/mostjs/core/

**Comment by StreetStrider** [comment]
@davidchase, should I hold off further PRs if any? And targeting modularized repos?

**Comment by davidchase** [comment]
@StreetStrider if you got more you can PR em here

**Pull request merged**
