### PR TITLE
Clarify stream end signal value

### PR DESCRIPTION
**Pull request by maciasello**
This PR includes documentation of end signal value. It supersedes #104 as the commit is included here too (it was rebased to current master). There is still some work to be done in the topic of end signal value as only simple cases were mentioned here. All the operations on streams need to be evaluated in terms of end signal value, but it was beyond my expertise (now). I'm opening new issue to handle the rest.

### CODE REVIEW

**Comment by maciasello** [comment]
Not sure why Travis fails as there were no changes besides docs/api.md

**Comment by briancavalier** [comment]
Kinda wild that your PR now includes my commit.  I'm cool with it, tho :)

**Comment by briancavalier** [comment]
Travis failed because there are 2 tests that currently have race conditions in them, just due to the way the tests are designed (ie badly, by me!).  I need to make time to refactor them.

**Comment by maciasello** [comment]
I'll rework the areas mentioned later today. In the meantime I filed #106 to track further doc improvement.

**Comment by maciasello** [comment]
First commit concerning #106 pushed. More to come.

**Comment by maciasello** [comment]
Will change to undefined in further commits. Enough for today :)

**Comment by maciasello** [comment]
Sorry for the tiny commits but I get spare moments here and there and don't want to have dangling changes waiting for too long in the WD.

**Comment by briancavalier** [comment]
No worries on the small commits, they can always be squashed/rebased later before merging.

**Comment by briancavalier** [comment]
Hey @maciasello, where do we stand on this?

**Comment by maciasello** [comment]
I've been buried under other stuff and this one got stale. I'll hopefully
get back to it this week.

pt., 27 mar 2015 o 02:09 użytkownik Brian Cavalier <notifications@github.com>
napisał:

**Comment by maciasello** [comment]
Ok. Long time no see, but I'm back and alive :) I'll get down to it in the near future.

**Comment by jasonkuhrt** [comment]
How is this going?

**Comment by briancavalier** [comment]
Closing this, but I'm going to start incrementally incorporating the info from this PR.  I'll try to cherry-pick where I can so that you get credit, @maciasello, because I certainly appreciate your work on this.

**Pull request closed without merging**
