### PR TITLE
cnd via unpkg

### PR DESCRIPTION
**Pull request by shrynx**
It is useful, when i am using it in something like JSBin, which i use a lot to give quick demos/tutorials .

### CODE REVIEW

**Comment by TylorS** [comment]
Hi @shrynx, I think this is a great idea! Would it be possible to add the non-minified version as well?
Perhaps something like

```html
<!-- unminified -->
<script src="https://unpkg.com/most/dist/most.js"></script>

<!-- minified -->
<script src="https://unpkg.com/most/dist/most.min.js"></script>
```

**Comment by briancavalier** [comment]
Thanks, @shrynx!  I like @TylorS's suggestion to add the example of using the unminified as well.  Will be very happy to merge this if you can add that :)

**Comment by davidchase** [comment]
:shipit:

**Comment by shrynx** [comment]
@briancavalier @TylorS Sure, I'll add it to the pull request.

**Comment by shrynx** [comment]
I know , this isn't anything significant but as everyone say , start with the docs 😃 
new to frp and I really love this project for its speed and simplicity, hope to make better contributions to it.

**Comment by davidchase** [comment]
welcome @shrynx 😄

**Pull request merged**
